from vector import Vector

FIRST_COLUMN = 0
LAST_COLUMN = 14
FIRST_ROW = 0
LAST_ROW = 14
FORBIDDEN_ROW = 15
RACK_ROW = 16
EXCHANGE_ROW = 17
LEFT_RACK_BOUND = 4
RIGHT_RACK_BOUND = 11
CENTER = 7

BLANK = ' '

MAX_RACK_SIZE = 7
MAX_WORD_LENGTH = 15
MIN_GROUP_LENGTH = 3
MAX_GROUP_LENGTH = 8

SQUARE_SIZE = 40
MARGIN = 1

DEFAULT_WIDTH = 680
DEFAULT_HEIGHT = 800
MINIMAL_WIDTH = 442
MINIMAL_HEIGHT = 526

UP = Vector(0, -1)
DOWN = Vector(0, 1)
LEFT = Vector(-1, 0)
RIGHT = Vector(1, 0)
DIRECTIONS = [UP, DOWN, LEFT, RIGHT]
